version: '3.8'

services:
  db:
    image: sqlite:latest
    restart: unless-stopped
    volumes:
      - ./db:/db
  web:
    build: .
    command: bash -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && python manage.py runserver 127.0.0.1:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db 
    env_file:
      - .env
    restart: always
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
  celery:
    build: .
    command: celery worker --app=notification_service --loglevel=info
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://127.0.0.1:6379
      - CELERY_RESULT_BACKEND=redis://127.0.0.1:6379
    depends_on:
      - redis
      - web
      - db
    restart: always
  dashboard:
    container_name: dashboard
    build: .
    command: flower --app=notification_service --port=5555 broker=redis://127.0.0.1:6379
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://127.0.0.1:6379
      - CELERY_RESULT_BACKEND=redis://127.0.0.1:6379
    depends_on:
      - redis
      - web
      - celery 
    restart: always